### ISSUE TITLE
Função CursoR:::listar_turmas_recentes() 

### ISSUE THREAD

**Issue by beatrizmilz** [curso-r/CursoR#3]
Função CursoR:::listar_turmas_recentes() não retorna curso r4ds-1mais recente (Julho/2020)

Pode ser esse slice que esteja causando isso:
https://github.com/curso-r/CursoR/blob/a407ef0a14761b00072343041a59ebeb598a40b0/R/utils.R#L93

**Comment by williamorim** [comment]
Oi, Bea

Para mim está aparecendo. O que aparece para você?

A ideia é retornar só as últimas 3 turmas mesmo, para sempre mostrar os materiais mais atualizados (embora os slides sempre vão ser iguais em todas).

``` r
CursoR:::listar_turmas_recentes("r4ds-1")
#> # A tibble: 3 x 3
#>   Turma         Material                         Github                         
#>   <chr>         <chr>                            <chr>                          
#> 1 Outubro de 2… https://curso-r.github.io/20201… https://github.com/curso-r/202…
#> 2 Julho de 2020 https://curso-r.github.io/20200… https://github.com/curso-r/202…
#> 3 Maio de 2020  https://curso-r.github.io/20200… https://github.com/curso-r/202…
```

<sup>Created on 2020-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by beatrizmilz** [comment]
Will, agora que eu percebi que a ordenação está do mais novo para o mais antigo. Não tinha percebido e achei que estava faltando o mais recente! Erro meu, desculpa. Vou fechar a issue!
